Delete room button
dan2811/yamaha pull request #34
Opened 2024-11-04 20:52 UTC by Mariphy

Hi, I added a delete room button and fixed a bug of the delete room procedure here

2024-11-05 23:32 UTC, dan2811 requested changes
Looks great, couple minor changes needed, but overall it's really good!

2024-11-05 23:32 UTC, dan2811 commented on src/app/_components/admin/DeleteRoomButton.tsx
> +      alert('Item deleted successfully');
use `toast` instead. Should be able to import it and you can use it to display success and fail messages. [Example usage](https://github.com/dan2811/yamaha/blob/a8b9ee378283c2f23f98320147ba2acf4882fa65/src/app/_components/admin/InstrumentPill.tsx#L30)

2024-11-05 23:32 UTC, dan2811 commented on src/app/_components/admin/DeleteRoomButton.tsx
This file is specific to deleting a room, so it can actually live right next to the page.tsx file that it is used in.

2024-11-05 23:32 UTC, dan2811 commented on src/app/_components/admin/ConfirmationModal.tsx
This file is specific to deleting a room too, so it can also live right next to the page.tsx it is used in.

2024-11-05 23:32 UTC, dan2811 commented on src/app/_components/admin/ConfirmationModal.tsx
The styling is lovely by the way! It looks great. In a real work setting you may need to consider accessibility more, but for this project it's perfect.

2024-11-19 00:14 UTC, Mariphy commented on src/app/_components/admin/ConfirmationModal.tsx
I added toast and moved the file. Looks like nothing broke on my side. Could you have a quick look that it resolves everything correctly, please?

2024-11-19 00:33 UTC, Mariphy commented on src/app/_components/admin/ConfirmationModal.tsx
Also, I resolved the merge conflicts with main, but the deployment is failing for some reason.

2025-01-20 20:19 UTC, dan2811 commented on src/app/(admin)/admin/settings/rooms/[id]/DeleteRoomButton.tsx
> +import ConfirmationModal from "../../../../../_components/admin/ConfirmationModal";
We can use an alias here to make the import a bit nicer. In the tsconfig I've set "~" as an alias for the src folder.

```suggestion
import ConfirmationModal from "~/app/_components/admin/ConfirmationModal";
```

2025-01-27 22:07 UTC, Mariphy commented
Could you please double check the deployment? I think it's failing, but I don't have access to the error message?

2026-01-24 16:05 UTC, closed without merging